apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ${app_domain}-tls
spec:
  secretName: ${app_domain}-tls
  dnsNames:
  - ${app_domain}
  acme:
    config:
    - http01:
        ingressClass: ${ingress_type}
      domains:
      - ${app_domain}
  issuerRef:
    name: ${cert_issuer}
    kind: ClusterIssuer