apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - ${app_domain}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ${app_domain}
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer