apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: ${cert_issuer}
spec:
  acme:
    server: ${cert_issuer_server}
    email: ${CNAB_P_CERT_EMAIL_ADDRESS}
    privateKeySecretRef:
      name: ${cert_issuer}-key
    http01: {}