kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${pv_name}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: ${pv_name}
  storageClassName: ${storage_class_name}