allowEmptyPassword: false
wordpressUsername: ${CNAB_P_WORDPRESS_USERNAME}
wordpressPassword: ${wordpress_password}
wordpressEmail: ${CNAB_P_WORDPRESS_EMAIL}
wordpressFirstName: ${CNAB_P_WORDPRESS_FIRSTNAME}
wordpressLastName: ${CNAB_P_WORDPRESS_LASTNAME}
wordpressBlogName: ${CNAB_P_WORDPRESS_BLOGNAME}
mariadb:
  enabled: false
livenessProbe:
  initialDelaySeconds: 600
  timeoutSeconds: 10
  periodSeconds: 20
  successThreshold: 1 
  failureThreshold: 10
readinessProbe:
  initialDelaySeconds: 300
  timeoutSeconds: 10
  periodSeconds: 20
  successThreshold: 1
  failureThreshold: 10
image:
  repository: ${wordpress_repository_name}
  tag: ${wordpress_tag}
externalDatabase:
  host: ${externalDatabase_host}
  user: ${externalDatabase_user}
  password: ${externalDatabase_password}
  database: ${externalDatabase_database}
  port: 3306
persistence:
  existingClaim: ${pv_name}
replicaCount: ${CNAB_P_WORDPRESS_RELICA_COUNT}
service:
  type: ClusterIP
ingress:
  enabled: true
  hosts:
  - name: ${app_domain}
    tls: ${enable_https}
    certManager: ${enable_https}
    tlsSecret: ${app_domain}-tls
    annotations:
      kubernetes.io/ingress.class: ${ingress_type}
      certmanager.k8s.io/cluster-issuer: ${cert_issuer}
      kubernetes.io/tls-acme: true